### PR TITLE
NavLeft test and code climate configs

### PR DESCRIPTION
**Pull request by reidysj**
# Description
NavLeft test and code climate configs

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, but not tested (may need new tests)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by michaelharms6010** [comment]
Test error shows `ENOENT: no such file or directory, open '/home/runner/work/My-School-FE/My-School-FE/package.json'`

**Comment by michaelharms6010** [comment]
Is this a script issue with no coverage script in package json? or does react handle it differently from node

**Comment by reidysj** [comment]
Literally just realized that as I was making lunch. Will fix shortly

On May 27, 2020 2:15 PM, "Michael Harms" <notifications@github.com> wrote:

Is this a script issue with no coverage script in package json? or does
react handle it differently from node

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lambda-School-Labs/My-School-FE/pull/44#issuecomment-634849331>,
or unsubscribe

**Comment by michaelharms6010** [comment]
enjoy lunch!

**Comment by michaelharms6010** [comment]
Does this run locally for you? I had to remove CI=true and the watch-all conditionals to get coverage to work locally. I'm running this atm: `"coverage": "yarn test --coverage --watchAll"` - not sure precisely what the CI flag / watchall logic are doing, I'm more lost than you for sure

**Comment by michaelharms6010** [comment]
Getting warmer... nice job. Notes for future generations: tests now hit this:

```
Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
Usage:
  cc-test-reporter upload-coverage [flags]
```

**Comment by michaelharms6010** [comment]
If you go to aws it sure looks like it built successfully. Not sure why the test is lagging on github.

**Pull request merged**
